[book]
authors = ["Yura Zatsepin"]
language = "en"
src = "src"
title = "ci-without-overhead"
description = "Woodpecker CI tutorial with some small real projects"

[output.html]
git-repository-url = "https://github.com/partysun/ci-without-overhead"
edit-url-template = "https://github.com/partysun/ci-without-overhead/edit/master/{path}"
no-section-label = true
